# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0485a26cc21597c533b8275c16cbbeba68bf97eca05e01e23df534916914d9cc9b1170c5e32c9ee3f5b0d9d0fa2147ed197dcedb2a4f9000c90f650e7c23e426

test:
  secret_key_base: 3a71be11173447ab27194e2ea900fbc24427fd64966dbe1ad429eadb9abdef008c8e7631ac7f3b719eb681910aed1f294f00e4e66b7dfcaf749dd43501861bed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
